# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_hat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='house_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='sorting_hat.House'),
        ),
    ]
