# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorting_hat', '0002_auto_20180119_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='house_id',
            new_name='house',
        ),
    ]
